# Generated by Django 4.2.9 on 2024-08-27 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('transfer', 'Transfer'), ('deposit_money', 'Deposit Money'), ('withdraw_money', 'Withdraw Money')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delta_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concept', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_historic_movements', to='bank.account')),
                ('user_account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historic_movements', to='bank.account')),
            ],
        ),
    ]
