# Generated by Django 4.2.9 on 2024-09-12 08:49

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedCommissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('country', models.CharField(choices=[('spain', 'Spain'), ('france', 'France'), ('portugal', 'Portugal')], max_length=20)),
                ('total_amount_commission', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
