# Generated by Django 4.2.9 on 2024-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_commissionscalculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionscalculated',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
