# Generated by Django 4.2.9 on 2024-08-27 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_historicmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicmovement',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_historic_movements', to='bank.account'),
        ),
    ]
