# Generated by Django 4.2.9 on 2024-08-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_historicmovement_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicmovement',
            old_name='user_account_number',
            new_name='source_account',
        ),
        migrations.RenameField(
            model_name='historicmovement',
            old_name='recipient',
            new_name='target_account',
        ),
        migrations.AlterField(
            model_name='historicmovement',
            name='concept',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
